### ISSUE TITLE
In FitModel: lower limit for disk_teff mysteriously changes to 100 K?

### ISSUE THREAD

**Issue by gabrielastro** [tomasstolker/species#112]
I am fitting photometry with an atmospheric model + a blackbody. I want to consider blackbodies down to 10 K and do
```
bounds['disk_teff'] = (10.0, 1700.0)
bounds['teff'] = …  # for the atmospheric model
…
fit = FitModel(…, bounds=bounds)
```
And indeed `species` prints:
```
Fitting 7 parameters:
   - teff
   - logg
   - radius
   - parallax
   - disk_teff
   - disk_radius
   - ism_ext

Uniform priors (min, max):
   - teff = (1500.0, 2100)
   - disk_teff = (10.0, 1700.0)
   - disk_radius = (0.1, 500.0)
   - ism_ext = (0.0, 30.0)
   - logg = (3.48, 5.48)
   - radius = (0.5, 5.0)
```
However, in the posteriors (corner plot), the probability is increasing towards disc_teff = 100 K but then truncated, and indeed in the (hidden :slightly_smiling_face:) `.txt` file from the `MultiNest` output directory, the samples are cut at 100 K. I checked carefully and do not think I am accidentally restricting some Teff to 100 K anywhere. Thanks if you can help!

**Comment by tomasstolker** [comment]
Could you share the posterior?

**Comment by gabrielastro** [comment]
Ah! Sorry, actually there are few values below 100 K! Then it might be only a coincidence (the number is not really round) and indeed I should try increasing "the upper bound for the blackbody radius"! I will report.

**Comment by gabrielastro** [comment]
That did it, thank you! The ~100 K was a coincidence indeed. I let the disc radius go to 2e4 RJ and got Tdisc ~ 60 K. Sorry and thanks for your quick help!
