### ISSUE TITLE
Make the reported luminosity be the luminosity only of the atmosphere

### ISSUE THREAD

**Issue by gabrielastro** [tomasstolker/species#113]
Currently, the `   - luminosity = ` reported under `Calculate multi-photometry` and plotted in the corner plot (as log(L/LSun)) is the (reddened) photospheric luminosity _PLUS_ the integrated luminosity of the additional blackbody.

I would like to suggest that the much more useful quantity is the atmospheric luminosity only; the (additional) blackbody is usually not an earnest fit that is reliable enough to be integrated, especially if no far-infrared data or so are available.

`species` already conveniently shows L_disc/L_atm in the corner plot to let the user check the importance of the blackbody, which is very nice. However, the main output of interest is the luminosity of the atmosphere, I would say, especially in the light of comparing the results from different atmospheric models.

The less obvious question is whether to report the de-reddened luminosity and/or the "empirical" one that comes from fitting a reddened atmospheric model. Both are useful: L_bol,empirical for comparing between observations and/or models, and L_bol,deredded for use with evolutionary models (assuming that the extinction is exterior enough to the planet for it not to affect its cooling, which is ok to first order or much better, e.g. for extinction really from the ISM).

Thanks to your help, I do have a script to compute the intrinsic and the de-reddened luminosities :nerd_face: but maybe it would be useful in general :slightly_smiling_face: and if the calculation were done automatically!

**Comment by gabrielastro** [comment]
(Thanks for adding the label.) This would affect also in a positive way the luminosity that can easily be added to the legend of `plot_spectrum` through `leg_param` for an easy overview. I guess `luminosity` should be renamed to be explicit.

And on a related note, it would be nice to be able to just add e.g. mass or, especially, luminosity to the legend entry, without however having to set all other parameters, especially since they are different for most model families. The current default settings are great and it would be nice to just have the option to add luminosity/mass/Bayesian evidence/… Thanks if this is not too much trouble to implement!

**Comment by tomasstolker** [comment]
Thanks for the suggestion! I have changed `luminosity` to `log_lum`, `log_lum_atm`, and `log_lum_disk`. You can use `get_parameters()` from `ReadModel` to select the model parameters and then add e.g. mass to create a `leg_param` list.

**Comment by gabrielastro** [comment]
Thanks a lot! Are these quantities de-reddened (i.e., the intrinsic total and partial luminosities) or the integrated reddened ones? I am guessing the latter. There would still be some use, especially in the corner plot, for the dereddened atmospheric luminosity especially, which of course by definition is simply L_atm,dereddened = 4 π σ Teff⁴.

**Comment by tomasstolker** [comment]
These are all intrinsic luminosities!

**Comment by tomasstolker** [comment]
Closing this issue since it has been resolved
