### ISSUE TITLE
Negative blackbody radius :)

### ISSUE THREAD

**Issue by gabrielastro** [tomasstolker/species#115]
Hello again! I am doing:
```
Pargrenzen = {}
Parnormprior = {}

Pargrenzen['disk_teff']   = (10., 1000.)
# needs to be present to "activate" the variable
#   even though we will set normal priors afterwards:
Pargrenzen['disk_radius'] = (0., 700.)

# eine gaußsche Kurve für 200 ± 200 RJup
Parnormprior['disk_radius'] = (200, 200.)

fit = FitModel(…, bounds=Pargrenzen, normal_prior=Parnormprior)
```
and get a best-fitting disc radius of… -6 RJup :).
![Bildschirmfoto von 2024-10-01 20-58-32](https://github.com/user-attachments/assets/4b8bcf49-cbe3-4b4a-b7d2-1978c7e5ab8e)
Actually, the mean is zero because there is a peak at +6 RJ too. However, e.g. the mass posterior is not symmetric: high-mass solutions are possible with a negative blackbody radius but not with +6 RJup.

Two things here: It would be good to restrict R to be positive, of course, but I thought that if both `bounds` and `normal_priors` are set, the bounds would truncate the `normal_priors`. I looked again but maybe I missed it in the documentation of `FitModel`. Is it the same behaviour for all parameters: the final prior not being the multiplication of the top-hat from `bounds` and the Gaußian from `normal_prior`?

**Comment by tomasstolker** [comment]
A negative radius means that the radius is used to account for a deficit in the observed flux compared to the atmosphere model. I have updated the prior use such that setting both `bounds` and `normal_priors` will use a truncated normal prior.

**Comment by gabrielastro** [comment]
Thanks a lot!
> A negative radius means that the radius is used to account for a deficit in the observed flux compared to the atmosphere model.

Just for completeness and out of interest: Since the radius enters only squared in F<sub>obs</sub> = F<sub>surf</sub> × (R/d)², I would have thought that this cannot be the reason… The flux contribution of the atmosphere is not negative either, I thought.

**Comment by tomasstolker** [comment]
Right it is squared! So the two peaks are presumably symmetric around zero?

**Comment by gabrielastro** [comment]
Yes, exactly! So once is "wasting computing power" by exploring symmetric solutions… Yet for some reason there was an asymmetry in the mass as noted above.

**Comment by gabrielastro** [comment]
(Sorry that the _x_ axis values were missing above but from the values indicated one can see that it is symmetric :wink:.) I think that in any case the radius should be limited to zero no matter what.
