### ISSUE TITLE
Smoothing spectral data

### ISSUE THREAD

**Issue by gabrielastro** [tomasstolker/species#117]
Hello! I added a spectrum by doing `database.add_object(…, spectrum=…)`. To plot this (e.g. after fitting), I do `objectbox = database.get_object(…)`. How can I plot a smoothed version of the data since it is noisy? Only `ModelBox`es, not `ObjectBox`es, have the `smooth_spectrum()` method. I guess somehow `from species.util.spec_util import smooth_spectrum` could help but then the user would need to repackage the spectrum into a `Box`. Is there an easy way of doing it? If not, could you please add it if it is useful? Thanks!

**Comment by tomasstolker** [comment]
My suggestion would be to use one of these smoothing options:
https://specutils.readthedocs.io/en/stable/manipulation.html
And add the spectrum by a different label to the `Database` with `add_object`.

**Comment by gabrielastro** [comment]
Ah! ok, so external pre-processing of the data. Fair enough! I was hoping for an in-`species` solution but doing it externally has advantages, of course. Thanks for your quick reply!
