### ISSUE TITLE
Discrepancy in meaning of C/O for certain models

### ISSUE THREAD

**Issue by muuud** [tomasstolker/species#121]
The Sonora Elf Owl models use a convention where the reported C/O value is not actually the true value, but a "multiplier" of the solar C/O ratio of 0.458. This can be seen in Table 1 [here](https://arxiv.org/pdf/2402.00756).

I would suggest replacing the grid points of [0.5, 1.0, 1.5, and 2.5] with the values [0.22,0.458, 0.687, and 1.12] so the definition can remain consistent with the other model grids.

**Comment by tomasstolker** [comment]
Thanks a lot for pointing out this issue! Also the case for Sonora Bobcat it seems:
https://zenodo.org/records/5063476
The same solar C/O value was presumably used for Sonora Bobcat?

**Comment by muuud** [comment]
I just went to reread the [original Bobcat paper](https://iopscience.iop.org/article/10.3847/1538-4357/ac141d), and it appears they make the same assumptions. The reference they cite is [Lodders 2010](https://arxiv.org/abs/0910.0811) but I believe that is a mistake, since that paper appears to claim C/O = 0.5. In a [different paper](https://arxiv.org/abs/2410.17169) by some colleagues with the same claim (C/O = 0.458) they instead cite [Lodders 2009](https://arxiv.org/abs/0901.1149) which interestingly reports a value of C/O = 0.457, although the .001 discrepancy might just be a rounding error.

**Comment by tomasstolker** [comment]
I have updated the C/O values in the filenames of the Elf Owl and Bobcat grids. You would need to remove the grids from your `data_folder` such that the new grids will be downloaded. Thanks again for pointing out this issue!

**Comment by tomasstolker** [comment]
Closing this issue since it has been resolved.
