### ISSUE TITLE
Adding Sonora Diamondback to library of grid models?

### ISSUE THREAD

**Issue by cianotoole11** [tomasstolker/species#122]
Hi there,

I am just curious about if the new Sonora model, 'Sonora Diamondback' will be added to the library of grid models as it would be a great addition to complement the other Sonora models already in this database.

Thanks!

**Comment by tomasstolker** [comment]
Thanks for the suggestion! I am happy to add the Diamondback grid, but has the data been published somewhere in the meanwhile? If you have a link then please let me know!

**Comment by cianotoole11** [comment]
Hi Tomas!

I've attached the Zenodo <https://zenodo.org/records/12735103> link here,
and this has all the models available.

Thank you!

**Comment by tomasstolker** [comment]
Thanks for the link! I have added a R=6000 grid with the 'sonora-diamondback' tag and a R=30000 grid with the 'sonora-diamondback-highres' tag. See `available_models()` of `Database` for more details on the grids. I will close this issue but please reopen if you have any questions or encounter any issue.
