### ISSUE TITLE
Small suggestions for CompareSpectra

### ISSUE THREAD

**Issue by gabrielastro** [tomasstolker/species#124]
About `CompareSpectra`, a few suggestions:

- [x] It would be great if one could have contours of constant (intrinsic) bolometric luminosity `Lbol` of the atmosphere!
- [x] [The tutorial](https://species.readthedocs.io/en/latest/tutorials/grid_comparison.html) is impressively helpful despite not containing prose yet—this speaks to the logic of the code and the quality of the documentation! Just to confirm: for every (log _g_, _T_<sub>eff</sub>) combination, it picks the best model amongst varying all the other parameter values (using also the interpolated models), in every case fitting for the radius as a scaling factor, yes? This kind of brief description could be added to the documentation.

- [x] `scale_spec` talks about matching spectral templates but that is not relevant when comparing to atmospheric models, right?

- [x] The `extra_param` option of `plot_grid_statistic()` is great! Maybe provide an option to move the legend in the plot (in one example, it was where contours pile up, while another corner was empty) or even—_caveat emptor_—turn it off?

~- Maybe there could be a way of including a second component (a blackbody), but maybe it would get too complicated, so I am just mentioning this.~

Thanks again for one more great tool in the toolbox.

**Comment by tomasstolker** [comment]
This has all been implemented so I am closing this issue. The last point would indeed add to much complexity to the function.

**Comment by gabrielastro** [comment]
Thank you very much!
- I agree that the possibility of a second component would be too much trouble (for the programmer and possibly for the user :wink:)
- Thanks a lot for adding the `log_lum` contours! One thing about that (sorry): use by default two decimal places and/or add an option to specify that number (or in general the format of the contour)? A precision of a few times 0.01 dex is typical, and currently I get -3.8, -3.8, -3.8, -3.9, -3.9, etc.. Thanks!
