### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by suvadip31** [tomasstolker/species#49]
I am getting several warnings and errors during `species` installation. I am installing it on windows 10 and python 3.9.6. What I followed is below:

1. `pip install --upgrade pip`
2. `pip install cython`
3. `pip install species`

Part of error I am getting is:

`error: Could not find module 'hdf5.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Loading library to get version: hdf5.dll`

`ERROR: Command errored out with exit status 1: 'c:\python\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.arg                                                                                     v[0] = '"'"'C:\\Users\\suvad\\AppData\\Local\\Temp\\pip-install-kb2icwhf\\h5py_2e14276aa53349df926b77e05bacce1f\\setup.py'"'"'                                                                                     ; __file__='"'"'C:\\Users\\suvad\\AppData\\Local\\Temp\\pip-install-kb2icwhf\\h5py_2e14276aa53349df926b77e05bacce1f\\setup.py'                                                                                     "'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools i                                                                                     mport setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'e                                                                                     xec'"'"'))' install --record 'C:\Users\suvad\AppData\Local\Temp\pip-record-60yn7xrd\install-record.txt' --single-version-exter                                                                                     nally-managed --compile --install-headers 'c:\python\Include\h5py' Check the logs for full command output.`

Any help would be great!

**Comment by tomasstolker** [comment]
Thanks for opening this issue, @suvadip31.

This seems to be an HDF5 or Windows problem. Could you try installing `h5py` to test if that works (i.e. `pip install h5py`)? If so, which version of `h5py` is installed?

**Comment by suvadip31** [comment]
Thank you for the reply! I managed to install Species on Linux (Ubuntu 20.04) but I am facing another problem there (I will create a new issue for that). I will try to install `h5py` on windows and let you know.

**Comment by suvadip31** [comment]
I tried `pip install h5py` on windows and it installs `h5py` `3.3.0`. I did not get any errors while installing.

**Comment by tomasstolker** [comment]
OK good. Installing `species` with `pip` still does not work?

If not, could you try cloning the repository from Github:
`git clone git@github.com:tomasstolker/species.git`

Install the dependencies manually:
`pip install -r requirements.txt`

And point the `PYTHONPATH` to the `species` folder?

See also:
https://species.readthedocs.io/en/latest/installation.html
