### ISSUE TITLE
Warning: 'PyMultiNest could not be imported.'

### ISSUE THREAD

**Issue by suvadip31** [tomasstolker/species#50]
I am getting this warning whenever I `import species`.  The details of warnings it shows are below:
```
ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html


ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory
/work/LAS/kerton-lab/suvadip/py3/lib/python3.8/site-packages/species/analysis/fit_model.py:26: UserWarning: PyMultiNest could not be imported.
  warnings.warn('PyMultiNest could not be imported.')
```
I checked and found `pymultinest` is already installed. Any help would be great! Thanks!

**Comment by tomasstolker** [comment]
To use `PyMultiNest`, it is required to manually build `MultiNest`. Please have a look at the instructions that you have posted in this issue.

The message is a warning though so `species` can still be used, apart from the functionalities that require `MultiNest`.

**Comment by suvadip31** [comment]
I noticed that `pymultinest` is already installed at `/path/to/dir/lib/python3.8/site-packages/`. Should I do something like below:

`export LD_LIBRARY_PATH=/path/to/dir/lib/python3.8/site-packages/`

**Comment by tomasstolker** [comment]
There is a difference between `PyMultiNest` and `MultiNest`. Both should be installed. You can find the installation instructions here:

https://johannesbuchner.github.io/PyMultiNest/install.html

`LD_LIBRARY_PATH` should point to the compiled `MultiNest` library.

**Comment by wbalmer** [comment]
@suvadip31 , if you're using conda for package management, you can easily install both multinest and pymultinest via conda without dealing with exporting the correct path manually.

https://anaconda.org/conda-forge/pymultinest

`conda install -c conda-forge pymultinest`
