### ISSUE TITLE
add ATMO-low logg model grid from Petrus+22?

### ISSUE THREAD

**Issue by wbalmer** [tomasstolker/species#61]
Hey Tomas! It would be useful to have access to the low-surface gravity ATMO grid computed for Petrus+22 to fit some of the companion's I'm working on right now. The paper is here (https://ui.adsabs.harvard.edu/abs/2022arXiv220706622P/abstract) and I believe the files are hosted here: https://noctis.erc-atmo.eu/fsdownload/pVzNaZXaK/petrus2022

**Comment by tomasstolker** [comment]
Hi William, thanks for the suggestion!

I have included the JWST (0.2 to 30 um at R = 3000) version of the grid, which can be added as `add_model('petrus2023')`. It seems that the paper is not yet accepted I think, hence I used 2023 in the name.

I noticed an issue with the filenames of the co0.7_p0.6 folder (C/O=0.7, [Fe/H]=+0.6). You can still use the grid, but just be careful if your use spectra from that regime. I have informed Simon so will upload a new grid once it has been fixed.

Hereby a test with `ReadModel` (the blackbody spectrum was to check that I had understood the flux units of the grid correctly):

![spectra_teff](https://user-images.githubusercontent.com/3204762/212102284-59e73b81-a137-4a89-af97-14544a0c94e1.png)

There is the `get_points` method of `ReadModel` to check the required parameters and their available range.

I also tried adding the high-resolution grid (0.2-2.5 um at R=10000) but there seems an issue with how some of the files were written (some data are missing) in one of the folders. This grid could also be added once the issue has been fixed.

You can pull the update from the `main` branch.

I hope that helps and let me know in case you have any questions or run into an issue 😊!

**Comment by wbalmer** [comment]
Thanks so much! just did a test and it works great! a bonus that i got a better fit to my data with this grid too :~)
