### ISSUE TITLE
interp2d deprecation in SciPy 1.10 leads to too many warnings printed during sampling

### ISSUE THREAD

**Issue by wbalmer** [tomasstolker/species#65]
interp2d deprecation in SciPy 1.10 leads to too many warnings printed during sampling when using the lognorm extinction priors in FitModel, resulting in a crash when using a Jupyter Notebook. source is dust_utils.interp_lognorm, line 417. my quick fix was just to import warnings and suppress warning output in the dust_utils.py directly, but according to [this](https://scipy.github.io/devdocs/notebooks/interp_transition_guide.html) transition guide, another function should be implemented.

**Comment by tomasstolker** [comment]
Thanks for opening this issue @wbalmer!

I have changed the use of `interp2d` to `RegularGridInterpolator` in PR #66, so the warnings should not appear anymore after pulling in the latest commit.

Hopefully that solves the issue but let me know otherwise!
