### ISSUE TITLE
TypeCheckError: argument "deredden" (None)

### ISSUE THREAD

**Issue by f4hzg** [tomasstolker/species#70]
Following the [Fitting data with a grid of model spectra](https://species.readthedocs.io/en/latest/tutorials/fitting_model_spectra.html) tutorial with a fresh installation of species leads to the error attached. The error is triggered when calling `database.add_companion(name='beta Pic b')`.

Setting deredden to Optional in species/data/database.py, line 824 solves the issue.

[error.log](https://github.com/tomasstolker/species/files/12665824/error.log)

**Comment by tomasstolker** [comment]
Thanks for opening this issue!

I see that you are using Python 3.11, which is not yet supported by `species`. The error does not occur with version 3.10.

If you run into any further errors then I could recommend using Python 3.10, but I will try to add support for Python 3.11 soon!

**Comment by f4hzg** [comment]
Ok, thanks! I forgot to check on Python 3.10. As a note, though, that's the only problem I encountered so far. It was a bit of a pain to install via pip because of the unsatisfied dependencies (especially numba), but it mostly works on 3.11.

**Comment by f4hzg** [comment]
Hi Tomas! Not sure it's the best way to do it, but I'm reopening this issue. because I have a simillar problem. Also in Python 3.11, running the tutorial, it crashes when running the fit.run_multinest, with again a type check error: `TypeCheckError: argument "spectrum" (None) is not a tuple`
[error.log](https://github.com/tomasstolker/species/files/12719472/error.log)
