### ISSUE TITLE
BEX Exoplanet Grids

### ISSUE THREAD

**Issue by maxwellmb** [tomasstolker/species#72]
Hi Tomas, 

I love the package! Just like William, I would love for someone to have another model grid added in. In my case, the BEX models from [Linder et al. 2019](https://ui.adsabs.harvard.edu/abs/2019A%26A...623A..85L/abstract). I would try to hack them in myself, but sadly I don't think I'll have time, so I thought I'd drop it here to see if anyone else might! 

Cheers, 
Max

**Comment by tomasstolker** [comment]
Hi Max,

Thanks for the suggestion! The BEX evolution data from Linder et al. can now be used with the latest release (v0.7.1):
https://github.com/tomasstolker/species/releases/tag/v0.7.1

There are several grids, e.g. different [M/H] and f_sed. All grids will be added with `add_isochrones('linder2019')`. Then, if you set `tag=None` in `ReadIsochrone` it will list the database tags that you can choose from.

I hope that helps!

**Comment by tomasstolker** [comment]
One more thing:

You can use the `get_filters` method of `ReadIsochrone` to list the filter names for which there are magnitudes available:
https://species.readthedocs.io/en/latest/tutorials/read_isochrone.html

**Comment by maxwellmb** [comment]
Incredible! I look forward to playing with it. Thanks for the quick response Tomas!
