### ISSUE TITLE
BT-NextGen (or similar stellar model) with Fe/H < 0?

### ISSUE THREAD

**Issue by wbalmer** [tomasstolker/species#74]
Hi Tomas! 

Would it be possible to add the low metal BT-NextGen grid points? Or perhaps there is a phoenix stellar grid with a range of metallicity? For instance 51 Eri A is Fe/H ~= -0.1 

I can get a single spectrum and ingest it to species (e.g. here https://phoenix.astro.physik.uni-goettingen.de/?page_id=16) , but it would be nice to be able to fit for Fe/H for these hosts.

**Comment by tomasstolker** [comment]
Hi @wbalmer,

Thanks for the suggestion! I checked the [SVO Theoretical Spectra](http://svo2.cab.inta-csic.es/svo/theory/newov2/index.php?models=bt-nextgen-agss2009) and was reminded that it was not possible to include the metallicity I think. The metallicity grid has only several points and these are different for each log(g) and also have differences in alpha enrichment.

See for example the available grid points for Teff=10000:
<img width="1052" alt="btnextgen" src="https://github.com/tomasstolker/species/assets/3204762/f40ea3fc-4ef8-4c33-a164-9d336638b5ca">

Do you know if the grid for which you provided a link is more regularly sampled?

**Comment by wbalmer** [comment]
A separate grid for low metallicity, alpha=0.4 seems reasonable given the data at hand? I'll need to read up on what effect the alpha value has on the actual spectrum, I assume enhanced alpha is standard for lower metallicites given that is what is hosted on SVO? but I need to brush up on my stellar evolution and synthesis...

**Comment by tomasstolker** [comment]
Yes exactly, from the figure on this [wikipedia](https://en.wikipedia.org/wiki/(%CE%B1/Fe)_versus_(Fe/H)_diagram) page I also understood that alpha enrichment inversely correlates with metallicity.

From that website:
_The diagrams are using abundance ratios that are normalised to the Sun (placing the Sun at (0,0) in the diagram) and allow to easily identify stars of the Galactic stellar high-alpha disk (historically known as the Galactic stellar [thick disk](https://en.wikipedia.org/wiki/Thick_disk)) via their typically enhanced in [α/Fe] and stars of the Galactic stellar low-alpha disk (historically known as the Galactic stellar [thin disk](https://en.wikipedia.org/wiki/Thin_disk)) having [α/Fe] as low as the Sun. It further allows to identify stars that are likely born at times or in environments very different to the stellar disk, typically metal-poor stars (with low [Fe/H] < -1) which likely belong to the [stellar halo](https://en.wikipedia.org/wiki/Stellar_halo) or [accreted](https://en.wikipedia.org/wiki/Accretion_(astrophysics)) features._

Might indeed be good to check the impact of the alpha parameter on the spectrum. Perhaps for a typical calibration it will not matter, or the effect is mainly in the optical.

I can add the low metallicity grid! Might be in the new year, so please remind me in case I forget 😉.

**Comment by wbalmer** [comment]
Hi Tomas! Sorry to bother you, I just wanted to bump this to the new year since this would be super helpful to have in the context of our AF Lep b paper this month. No big rush, though, since I have preliminary analyses I can run without having the perfect absolute flux for that spectrum.

**Comment by tomasstolker** [comment]
Downloading the spectra from SVO was extremely slow because of the high resolution. Instead I have downloaded [synphot5_pheonix-models.tar](https://archive.stsci.edu/hlsps/reference-atlases/hlsp_reference-atlases_hst_multi_pheonix-models_multi_v3_synphot5.tar) from https://archive.stsci.edu/hlsp/reference-atlases. It doesn't mention the alpha value, but it does include subsolar metallicites.

**Comment by tomasstolker** [comment]
It seems that the PHOENIX spectra form the REFERENCE-ATLASES have been resampled to a low resolution a several hundred. For calibrating photometry that will be fine, but you want to use this for calibrating a GRAVITY spectra, right? I will download it from SVO instead and will see how far it gets today...

**Comment by wbalmer** [comment]
Hi Tomas, did that download go okay?

**Comment by tomasstolker** [comment]
Yes I managed to download the subsolar grid! Turned out that downloading from SVO in several chunks was much faster than downloading all Teff at once. I will try find some time this afternoon to resample and upload it for `species`.

**Comment by tomasstolker** [comment]
Hi @wbalmer! I have added the subsolar metallicity grid of BT-NextGen as `'bt-nextgen-subsolar'` in commit 05bf3d173a725a575da7a4d88830cde6aae12abe. These spectra all have [alpha/Fe] = 0.4 with the largest metallicity being -0.5. Solar metallicity is not included since those spectra mainly had [alpha/Fe] = 0.0.

The grid was not fully regularly sampled, so you have to be a bit careful when using/fitting spectra close to any of the missing grid points, because those fluxes are set to zero. For a best fit spectrum, it is therefore useful to check with `ReadModel` what the spectra at the nearest grid points look like.

**Comment by tomasstolker** [comment]
Hereby an example of spectra from 5000 to 7000 K:
![spectra_teff](https://github.com/tomasstolker/species/assets/3204762/17762dc3-4232-4afe-9a7e-add3c72e9892)

**Comment by tomasstolker** [comment]
As function of log(g):
![spectra_logg](https://github.com/tomasstolker/species/assets/3204762/20933874-bd84-4ab6-b0fa-aeb0fae1692e)

**Comment by wbalmer** [comment]
Thanks again Tomas, I really appreciate this. I've tested adding and interpolating the grid and everything works great.
