### ISSUE TITLE
Enhancing plot_spectrum a bit

### ISSUE THREAD

**Issue by gabrielastro** [tomasstolker/species#88]
A few suggested improvements for `plot_spectrum`:

1. The disc parameters are not included in the legend (when no label is specified), which is "dangerous" because there is no reminder on the plot that such a component was included. I was going to suggest extending `leg_param` to include all parameters in the `ModelBox` but it gives `UserWarning: The 'disk_teff' parameter in 'leg_param' is not a parameter of 'atmo-neq-weak' so it will not be included with the legend.` and the same for `disk_radius` even though `ModelBox.open_box()` listed them.

2. Can one have the data points underneath (underplot) the model points? Changing the order of the boxes passed to `plot_spectrum()` surprisingly does not have this effect.
  
3. Would it be easy to have a "staircase" (with steps centered at the x values) for the theoretical spectrum? This would be good when looking at only small spectral regions, as a clear reminder of the finite resolution.
  
4. It would be nice to be able to underplot only the blackbody (or, in general, "the other model" when using two components), to see more clearly its contribution, and maybe and/or the pure-atmospheric model. If not much more work to program: have for each contribution the option of underplotting it?

In any case, the routine is already very nice!

**Comment by gabrielastro** [comment]
3. Sorry (I am not an expert with this at all): I discovered that specifying 'ds' or `'drawstyle' : 'steps-mid'` in `plot_kwargs` is what is needed :heavy_check_mark:. Maybe make this the default for the theoretical spectra, as a healthy reminder that resolution is finite?

**Comment by tomasstolker** [comment]
Hello! There is the `get_object` method of `Database`, and there are also the `ReadObject` functionalities:
https://species.readthedocs.io/en/latest/tutorials/companion_data.html

**Comment by gabrielastro** [comment]
4. Thanks! :heavy_check_mark: I realised my silly mistake: one needs to do `lmbd = objectbox.spectrum['midres'][0][:,0]` (I was doing `…[:][0]` instead). Using `ReadObject()` as in the "Companion data" tutorial as you suggested also works, as a synonym.

**Comment by tomasstolker** [comment]
For setting the level/order of the plot items, you can use the `zorder` parameter in the `kwargs` dictionary, although the use of that parameter is sometime a bit confusing, but that is an Matplotlib issue (?).

**Comment by tomasstolker** [comment]
For adding blackbody components, you can create `ModelBox` objects as:

```
param_planck = {'teff': param['disk_teff'], 'radius': param['disk_radius'], 'parallax': best['parallax']}
read_planck = species.ReadPlanck(wavel_range=(1.0, 10.))
planck_spec = read_planck.get_spectrum(model_param=param_planck, spec_res=100.)
```

And add `planck_spec` to the list of `boxes` of `plot_spectrum.

**Comment by gabrielastro** [comment]
2. (zorder) Thanks! How can I at least see the `zorder` values used by the other elements to then call plot routine again with an appropriate value? Or could you let the user specify and array of `zorder` values for the different components?

**Comment by tomasstolker** [comment]
You can just set a `zorder` for each item in your plot, so it will overwrite the default values.

**Comment by gabrielastro** [comment]
4. (showing the blackbody component) Perfect, thank you :heavy_check_mark:! Maybe add this to the tutorial? `ReadPlanck` is used in a tutorial on [colour–magnitude diagrams](https://species.readthedocs.io/en/latest/tutorials/color_magnitude_broadband.html#Color-magnitude-diagram:-broadband-filters) but `read_planck.get_spectrum()` is not showcased there.

**Comment by tomasstolker** [comment]
Should now be possible to include `disk_teff` and `disk_radius` in the `leg_param` (see commit [093df1d](https://github.com/tomasstolker/species/commit/093df1dc8294f3277bd8f38e6dbb292167a89dc8)).

**Comment by gabrielastro** [comment]
1. (adding the disc parameters automatically to the legend) Thanks a lot! I get however:
```
[…]/species/plot/plot_spectrum.py in plot_spectrum(boxes, filters, residuals, plot_kwargs, envelope, xlim, ylim, ylim_res, scale, title, offset, legend, figsize, object_type, quantity, output, leg_param, param_fmt, grid_hspace, inc_model_name, units)                                                                                                                                                           
    545                     param = box_item.parameters.copy()
    546 
--> 547                     label = create_model_label(
    548                         model_param=param,
    549                         object_type=object_type,

[…]/species/util/plot_util.py in create_model_label(model_param, object_type, model_name, inc_model_name, leg_param, param_fmt)
   1506 
   1507     if len(leg_param) == 0:
-> 1508         read_mod = ReadModel(model_name)
   1509         leg_param = read_mod.get_parameters()
   1510         check_param = list(model_param.keys())

[…]/species/read/read_model.py in __init__(self, model, wavel_range, filter_name)
    125 
    126         # Test if the spectra are present in the database
--> 127         hdf5_file = self.open_database()
    128         hdf5_file.close()
    129 

/whome/adk427f/Dokumente/folk/TomasStolker/species/species/read/read_model.py in open_database(self)
    160             # before running FitModel with MPI
    161             with h5py.File(self.database, "a") as hdf5_file:
--> 162                 add_model_grid(self.model, self.data_folder, hdf5_file)
    163 
    164         return h5py.File(self.database, "r")

[…]/species/data/model_data/model_spectra.py in add_model_grid(model_name, input_path, database, wavel_range, teff_range, spec_res, unpack_tar)
     79 
     80     else:
---> 81         raise ValueError(
     82             f"The {model_name} atmospheric model is not available. "
     83             "Please choose one of the following models: "

ValueError: The planck atmospheric model is not available. Please choose one of the following models…
```
So I guess somehow `blackbody` instead of `planck` is needed somewhere…

**Comment by tomasstolker** [comment]
Hmmm if you fitted `disk_teff` and `disk_radius` then the model should already have been included in the database?

It is a bit hard to tell what you are trying to do. Could you share the code that you are running?

**Comment by gabrielastro** [comment]
Indeed, `disk_teff` and `disk_radius` are present in the data. I am trying to underplot the blackbody component separately, with:
```
param_planck = {'teff': best['disk_teff'],  'radius': best['disk_radius'], 'parallax': best['parallax']}
read_planck = ReadPlanck(wavel_range=(0.1, 30.))
planck_spec = read_planck.get_spectrum(model_param=param_planck, spec_res=3000.)
```
and passing this as a `box` to `plot_spectrum`. This is causing the problem, I see now.

**Comment by tomasstolker** [comment]
Are you sure? Perhaps I broke something because the extra blackbody component (from `disk_teff` and `disk_radius`) should be included in the spectrum.

**Comment by gabrielastro** [comment]
Pretty much… I think there are currently two problems: 1.) I cannot add the blackbody (`planck_spec`), and 2.) the `best` model (which includes `disk_teff` and `disk_radius`) gets plotted without the blackbody component (missing at plot time and in the legend). Also, I cannot set e.g. `leg_param= ['logg', 'radius']` in `plot_spectrum`, getting `AttributeError: 'list' object has no attribute 'keys'` at `[…]/species/util/plot_util.py:1517` (but maybe this is a different issue).

**Comment by tomasstolker** [comment]
Can you share the code that you are running (offline is also fine)? That would be easier bug fixing

**Comment by gabrielastro** [comment]
Thanks a lot :+1:! Now it works perfectly.
