### ISSUE TITLE
wavelength / spectral spacing for exo-rem-highres grid 

### ISSUE THREAD

**Issue by wbalmer** [tomasstolker/species#94]
Hi Tomas,

I'm really interested in using the exo-rem highres grid for our AF Lep b analysis, but `FitModel` stalls at interpolating the grid on our SPHERE IFS spectrum because the wavelength of that spectrum is not uniform. 

I get this warning, but have to manually kill the process.

Interpolating SPHERE...

/Users/wbalmer/species/species/util/spec_util.py:122: UserWarning: The wavelength spacing is not uniform (3.152470770057788e-05 +/- 6.685785633535913e-06). The smoothing with the Gaussian kernel requires either the spectral resolution or the wavelength spacing to be uniformly sampled.
  warnings.warn(`

How would you recommend I proceed? Is there a way to resample the exo-rem-highres to a uniform spectral resolution? I tried 

`database.add_model(model=model_choice, teff_range=(700., 1300.), wavel_sampling=2000.)`

but to no avail.

**Comment by wbalmer** [comment]
I was able to fix this by injesting the model like

`database.add_model(model=model_choice, teff_range=(700., 1300.), wavel_sampling=2000., wavel_range=(0.9,5))`

**Comment by tomasstolker** [comment]
Thanks for noticing that! Reopening this issue because the warning should not have occurred because all grid have been resampled to a constant lambda/Delta_lambda.

**Comment by tomasstolker** [comment]
Hm I am not sure what caused the warning to show up. I am not able reproduce it.

It is indeed anyway a good idea to use `wavel_sampling` and `wavel_range` (if the data allows) with a high-resolution grid, to limit the disk storage and speed up the interpolation at the start of `FitModel`.

**Comment by wbalmer** [comment]
I think it could be for two reasons, either because my SPHERE spectrum has some nans (e.g. some upper limit values) or because it is extracted on an uneven wavelength grid that is more true to the instrument's wavelength calibration (the extraction comes from our SPHERE-DC friends). Probably the latter? I can send you the file if you'd like to use it to bug test.

**Comment by wbalmer** [comment]
Ah, good to note! Thanks for updating this Tomas.
