### ISSUE TITLE
pypi package version

### ISSUE THREAD

**Issue by nenasedk** [tomasstolker/species#95]
The current version of `species` available on pypi is somewhat behind the current master version. 
This issue for petitradtrans (https://gitlab.com/mauricemolli/petitRADTRANS/-/issues/64) will be resolved when the pypi version is updated, and the changes to SyntheticPhotometry are reflected in the pip installed version of the package.

**Comment by tomasstolker** [comment]
Good idea, it is about time!

Just updated the package to version 0.0.8, also on PyPI:
https://github.com/tomasstolker/species/releases/tag/v0.8.0
