### ISSUE TITLE
Different fsed for cloud species in retrieval

### ISSUE THREAD

**Issue by wbalmer** [tomasstolker/species#96]
Hi Tomas! In [petitRADTRANS.retrieval.cloud_cond](https://gitlab.com/mauricemolli/petitRADTRANS/-/blob/2.7.3_dev/petitRADTRANS/retrieval/cloud_cond.py?ref_type=heads), you can set a global fsed and Kzz, or a fsed for each cloud species and a global fsed. How difficult would this be to implement in species? I think it would be useful, given that different clouds might condense or be lofted at different rates, resulting in different exponential decays in opacity.

**Comment by tomasstolker** [comment]
Yes I agree that would be interesting to test! You meant the option to fit fsed for each cloud species separately and global Kzz?

**Comment by wbalmer** [comment]
Yes, exactly! Doing so would allow me to reproduce exactly ZJ's retrieval tested on AF Lep b in his 2023 paper, but including some of the nice species only features, like fitting the GP for the covariance matrix estimation.

**Comment by tomasstolker** [comment]
I have implemented the `global_fsed` parameter in commit 055af59e3598dc9d970e268b1e255884e2a7ae24. You can set it to `False` for retrieving the `fsed` parameter for each cloud species individually. For each species, it will use the same `fsed` range that is specified in `bounds`.

I did some brief testing but please let me know if this works fine!

**Comment by wbalmer** [comment]
I ran some tests overnight and it appears to work great! I'll let you know how the converged results look.
